name: Deploy Internal Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ibm-x86-64-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git for GitHub Enterprise
        run: |
          git config --global url."https://${{ github.token }}@github.ibm.com/".insteadOf "ssh://git@github.ibm.com/"
          git config --global url."https://${{ github.token }}@github.ibm.com/".insteadOf "git@github.ibm.com:"
          git config --list

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        env:
          GIT_TERMINAL_PROMPT: 0
        run: npm install

      - name: Build internal documentation
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .docs-engine/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ibm-x86-64-small
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4